Repository modelpack/model-spec, pull requests merged in 2025-07, with the labels that each got.

#87 chore: add pr-labels actions
  .github/workflows/pr-labels.yml
Labels: enhancement

#88 chore: add issue templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement

#99 docs: align to Sandbox name
  code-of-conduct.md
  schema/example_test.go
  schema/schema.go
  schema/validator.go
  specs-go/v1/annotations.go
  specs-go/v1/config.go
  specs-go/v1/mediatype.go
Labels: documentation

#101 fix(docs): fix JSON in doc and ci/GHA linting
  docs/config.md
Labels: bug

#103 Add CNCF copyright footer text
  README.md
Labels: documentation

#102 docs: add OpenSSF Best Practices badge
  README.md
Labels: documentation
